import { describeRef, orientReference, primaryKeyOf } from "./orient";
import { baseType, defaultOf } from "./converters/shared";
import { sqlDefault } from "./converters/sql";
import type { DbmlEnum, DbmlField, DbmlRef, DbmlSchema, DbmlTable } from "./types";

/**
 * The SQL that takes a database from `before` to `after` — what "Comparar" hands over once it has
 * shown what changed.
 *
 * Built from the two **models**, like the diff it accompanies, so a document that only moved a
 * table or reworded a setting migrates to nothing. The statements are ordered the way a database
 * needs them: foreign keys that are going come off first (a table cannot be dropped while
 * something points at it), then tables go, types arrive, tables arrive, columns change, and the new
 * foreign keys go on last, when everything they point at exists.
 *
 * **What it cannot know is said, not guessed.** DBML does not name constraints, so a dropped
 * foreign key or unique constraint is dropped by the name this app's own generator gives it —
 * a database built another way may call it something else, and the statement carries a comment
 * saying so. A change that loses data (dropping a column, narrowing a type) is emitted, because that
 * is what the new schema says, but it is marked. A `NOT NULL` column added without a default is
 * flagged, since it fails on a table with rows in it.
 */

export type MigrationDialect = "postgresql" | "mysql";

interface Dialect {
  quote: (name: string) => string;
  type: (field: DbmlField, schema: DbmlSchema) => string;
  identity: string;
}

/** The DBML type as the dialect spells it. Arguments are kept; only the base name is mapped. */
function mapType(type: string, table: Record<string, string>): string {
  const base = baseType(type);
  const mapped = table[base];
  if (!mapped) return type.replace(/\[\]$/, "").toUpperCase();
  // Keep `(255)` / `(10,2)` when the target type takes it.
  const args = type.match(/\(.*\)/)?.[0] ?? "";
  return /\(/.test(mapped) ? mapped : `${mapped}${args}`;
}

const PG_TYPES: Record<string, string> = {
  datetime: "TIMESTAMP",
  timestamptz: "TIMESTAMPTZ",
  blob: "BYTEA",
  binary: "BYTEA",
  tinyint: "SMALLINT",
  double: "DOUBLE PRECISION",
  nvarchar: "VARCHAR",
};

const MYSQL_TYPES: Record<string, string> = {
  serial: "INT",
  bigserial: "BIGINT",
  uuid: "CHAR(36)",
  jsonb: "JSON",
  timestamptz: "TIMESTAMP",
  bytea: "BLOB",
  "double precision": "DOUBLE",
  money: "DECIMAL(19,4)",
  inet: "VARCHAR(45)",
  nvarchar: "VARCHAR",
};

function enumOf(field: DbmlField, schema: DbmlSchema): DbmlEnum | undefined {
  const base = baseType(field.type);
  return schema.enums.find((entry) => entry.name.toLowerCase() === base || entry.id.toLowerCase() === base);
}

const DIALECTS: Record<MigrationDialect, Dialect> = {
  postgresql: {
    quote: (name) => `"${name}"`,
    type: (field, schema) => {
      const asEnum = enumOf(field, schema);
      if (asEnum) return `"${asEnum.name}"`;
      return mapType(field.type, PG_TYPES);
    },
    identity: "GENERATED BY DEFAULT AS IDENTITY",
  },
  mysql: {
    quote: (name) => `\`${name}\``,
    type: (field, schema) => {
      // MySQL has no named enum type: the values travel with each column.
      const asEnum = enumOf(field, schema);
      if (asEnum) return `ENUM(${asEnum.values.map((value) => `'${value.name.replace(/'/g, "''")}'`).join(", ")})`;
      // A bare `varchar` is legal DBML and legal PostgreSQL, and a syntax error in MySQL.
      if (/^n?varchar$/i.test(field.type.trim())) return "VARCHAR(255)";
      return mapType(field.type, MYSQL_TYPES);
    },
    identity: "AUTO_INCREMENT",
  },
};

function qualified(table: DbmlTable, dialect: Dialect): string {
  return table.schema === "public"
    ? dialect.quote(table.name)
    : `${dialect.quote(table.schema)}.${dialect.quote(table.name)}`;
}

/** A whole column definition — what `ADD COLUMN` and MySQL's `MODIFY COLUMN` both take. */
function columnDefinition(
  field: DbmlField,
  schema: DbmlSchema,
  kind: MigrationDialect,
  inlineKey: boolean,
): string {
  const dialect = DIALECTS[kind];
  const parts = [`${dialect.quote(field.name)} ${dialect.type(field, schema)}`];
  if (field.increment) parts.push(dialect.identity);
  if (field.notNull || field.pk) parts.push("NOT NULL");
  const value = field.increment ? null : defaultOf(field);
  if (value) parts.push(`DEFAULT ${sqlDefault(value, kind)}`);
  if (field.unique && !field.pk) parts.push("UNIQUE");
  if (inlineKey) parts.push("PRIMARY KEY");
  if (kind === "mysql" && field.note) parts.push(`COMMENT '${field.note.replace(/'/g, "''")}'`);
  return parts.join(" ");
}

function createTable(table: DbmlTable, schema: DbmlSchema, kind: MigrationDialect): string[] {
  const dialect = DIALECTS[kind];
  const key = primaryKeyOf(table);
  const lines = table.fields.map(
    (field) => `  ${columnDefinition(field, schema, kind, key.length === 1 && key[0] === field.name)}`,
  );
  if (key.length > 1) lines.push(`  PRIMARY KEY (${key.map(dialect.quote).join(", ")})`);
  return [`CREATE TABLE ${qualified(table, dialect)} (`, lines.join(",\n"), ");"];
}

/** A reference, keyed the way `diff.ts` keys it — both ends and both cardinalities. */
function refKey(ref: DbmlRef): string {
  return `${ref.from.table}.${ref.from.fields.join("+")} ${ref.from.relation}-${ref.to.relation} ${ref.to.table}.${ref.to.fields.join("+")}`;
}

/** The constraint name this app's generator gives a foreign key — see `converters/sql.ts`. */
function fkName(child: DbmlTable, fields: string[]): string {
  return `fk_${child.name}_${fields.join("_")}`;
}

function uniqueName(table: DbmlTable, column: string): string {
  return `uq_${table.name}_${column}`;
}

/** The foreign key a reference stands for, oriented by evidence (see `orient.ts`), or why not. */
function foreignKey(
  schema: DbmlSchema,
  ref: DbmlRef,
): { child: DbmlTable; parent: DbmlTable; childFields: string[]; parentFields: string[] } | string {
  const oriented = orientReference(schema, ref);
  if (oriented.kind === "many-to-many") return `${describeRef(ref)}: a many-to-many needs a join table`;
  if (oriented.kind === "ambiguous") {
    return `${describeRef(ref)}: a one-to-one where nothing says which side holds the key`;
  }
  const child = schema.tables.find((table) => table.id === oriented.child.table);
  const parent = schema.tables.find((table) => table.id === oriented.parent.table);
  if (!child || !parent) return `${describeRef(ref)}: a table it names is not in the schema`;
  return { child, parent, childFields: oriented.child.fields, parentFields: oriented.parent.fields };
}

export function migrationSql(before: DbmlSchema, after: DbmlSchema, kind: MigrationDialect): string {
  const dialect = DIALECTS[kind];
  const q = dialect.quote;
  const out: string[] = [];
  const section = (lines: string[]) => {
    if (lines.length > 0) out.push(...lines, "");
  };

  const beforeTables = new Map(before.tables.map((table) => [table.id, table]));
  const afterTables = new Map(after.tables.map((table) => [table.id, table]));
  const beforeRefs = new Map(before.refs.map((ref) => [refKey(ref), ref]));
  const afterRefs = new Map(after.refs.map((ref) => [refKey(ref), ref]));
  const droppedTables = [...beforeTables.values()].filter((table) => !afterTables.has(table.id));
  const addedTables = [...afterTables.values()].filter((table) => !beforeTables.has(table.id));

  // 1. Foreign keys that go — including every one that points at, or out of, a table that goes.
  const dropKeys: string[] = [];
  for (const [key, ref] of beforeRefs) {
    if (afterRefs.has(key)) continue;
    const fk = foreignKey(before, ref);
    if (typeof fk === "string") continue;
    // A key on a table that is itself being dropped goes with the table.
    if (!afterTables.has(fk.child.id)) continue;
    const name = q(fkName(fk.child, fk.childFields));
    dropKeys.push(
      `-- named as CodeFlow names it; a database created another way may call it something else`,
      kind === "mysql"
        ? `ALTER TABLE ${qualified(fk.child, dialect)} DROP FOREIGN KEY ${name};`
        : `ALTER TABLE ${qualified(fk.child, dialect)} DROP CONSTRAINT IF EXISTS ${name};`,
    );
  }
  section(dropKeys);

  // 2. Tables that go. Their own keys and the rows in them go too — which is what dropping means.
  section(
    droppedTables.map((table) =>
      kind === "mysql"
        ? `DROP TABLE ${qualified(table, dialect)};`
        : `DROP TABLE ${qualified(table, dialect)} CASCADE;`,
    ),
  );

  // 3. Enum types (PostgreSQL only: MySQL's enums are part of each column, handled with it).
  const beforeEnums = new Map(before.enums.map((entry) => [entry.id, entry]));
  const afterEnums = new Map(after.enums.map((entry) => [entry.id, entry]));
  if (kind === "postgresql") {
    const types: string[] = [];
    for (const entry of afterEnums.values()) {
      const was = beforeEnums.get(entry.id);
      const values = entry.values.map((value) => value.name);
      if (!was) {
        types.push(
          `CREATE TYPE ${q(entry.name)} AS ENUM (${values.map((value) => `'${value.replace(/'/g, "''")}'`).join(", ")});`,
        );
        continue;
      }
      const old = was.values.map((value) => value.name);
      for (const value of values.filter((name) => !old.includes(name))) {
        types.push(`ALTER TYPE ${q(entry.name)} ADD VALUE IF NOT EXISTS '${value.replace(/'/g, "''")}';`);
      }
      for (const value of old.filter((name) => !values.includes(name))) {
        types.push(
          `-- ${entry.name} lost '${value}': PostgreSQL cannot drop an enum value — recreate the type if it must go`,
        );
      }
    }
    section(types);
  }

  // 4. Tables that arrive.
  for (const table of addedTables) section(createTable(table, after, kind));

  // 5. Columns of tables on both sides.
  for (const table of afterTables.values()) {
    const was = beforeTables.get(table.id);
    if (!was) continue;
    const target = qualified(table, dialect);
    const lines: string[] = [];
    const oldFields = new Map(was.fields.map((field) => [field.name, field]));
    const newFields = new Map(table.fields.map((field) => [field.name, field]));

    for (const field of table.fields) {
      const old = oldFields.get(field.name);
      if (!old) {
        if (field.notNull && field.default === null && !field.increment) {
          lines.push(`-- ${table.name}.${field.name} is NOT NULL with no default: a table with rows needs one first`);
        }
        lines.push(`ALTER TABLE ${target} ADD COLUMN ${columnDefinition(field, after, kind, false)};`);
        continue;
      }
      const typeChanged = dialect.type(old, before) !== dialect.type(field, after);
      const nullChanged = old.notNull !== field.notNull && !field.pk;
      const defaultChanged = old.default !== field.default;
      const noteChanged = old.note !== field.note;

      if (kind === "mysql") {
        // MySQL restates the whole column; one statement covers type, nullability and default.
        if (typeChanged || nullChanged || defaultChanged || noteChanged || old.increment !== field.increment) {
          if (typeChanged) {
            lines.push(
              `-- ${table.name}.${field.name}: ${dialect.type(old, before)} → ${dialect.type(field, after)}; check the data fits`,
            );
          }
          lines.push(
            `ALTER TABLE ${target} MODIFY COLUMN ${columnDefinition({ ...field, unique: false }, after, kind, false)};`,
          );
        }
      } else {
        const column = `ALTER TABLE ${target} ALTER COLUMN ${q(field.name)}`;
        if (typeChanged) {
          lines.push(
            `-- ${table.name}.${field.name}: ${dialect.type(old, before)} → ${dialect.type(field, after)}; check the data fits`,
          );
          lines.push(`${column} TYPE ${dialect.type(field, after)} USING ${q(field.name)}::${dialect.type(field, after)};`);
        }
        if (nullChanged) lines.push(`${column} ${field.notNull ? "SET" : "DROP"} NOT NULL;`);
        if (defaultChanged) {
          const value = defaultOf(field);
          lines.push(value ? `${column} SET DEFAULT ${sqlDefault(value, kind)};` : `${column} DROP DEFAULT;`);
        }
        if (noteChanged) {
          lines.push(
            `COMMENT ON COLUMN ${target}.${q(field.name)} IS ${field.note ? `'${field.note.replace(/'/g, "''")}'` : "NULL"};`,
          );
        }
        if (old.increment !== field.increment) {
          lines.push(
            field.increment
              ? `${column} ADD ${dialect.identity};`
              : `${column} DROP IDENTITY IF EXISTS;`,
          );
        }
      }

      if (old.unique !== field.unique && !field.pk && !old.pk) {
        const name = q(uniqueName(table, field.name));
        if (field.unique) {
          lines.push(`ALTER TABLE ${target} ADD CONSTRAINT ${name} UNIQUE (${q(field.name)});`);
        } else {
          lines.push(`-- named as CodeFlow names it; a database created another way may call it something else`);
          lines.push(
            kind === "mysql"
              ? `ALTER TABLE ${target} DROP INDEX ${name};`
              : `ALTER TABLE ${target} DROP CONSTRAINT IF EXISTS ${name};`,
          );
        }
      }
    }
    for (const field of was.fields) {
      if (newFields.has(field.name)) continue;
      lines.push(`-- drops ${table.name}.${field.name} and everything in it`);
      lines.push(`ALTER TABLE ${target} DROP COLUMN ${q(field.name)};`);
    }

    const oldKey = primaryKeyOf(was);
    const newKey = primaryKeyOf(table);
    if (oldKey.join(",") !== newKey.join(",")) {
      if (kind === "mysql") {
        const parts = [
          ...(oldKey.length > 0 ? ["DROP PRIMARY KEY"] : []),
          ...(newKey.length > 0 ? [`ADD PRIMARY KEY (${newKey.map(q).join(", ")})`] : []),
        ];
        if (parts.length > 0) lines.push(`ALTER TABLE ${target} ${parts.join(", ")};`);
      } else {
        if (oldKey.length > 0) {
          lines.push(`ALTER TABLE ${target} DROP CONSTRAINT IF EXISTS ${q(`${table.name}_pkey`)};`);
        }
        if (newKey.length > 0) lines.push(`ALTER TABLE ${target} ADD PRIMARY KEY (${newKey.map(q).join(", ")});`);
      }
    }
    section(lines);
  }

  // 6. Foreign keys that arrive, once every table they name exists.
  const addKeys: string[] = [];
  for (const [key, ref] of afterRefs) {
    if (beforeRefs.has(key)) continue;
    const fk = foreignKey(after, ref);
    if (typeof fk === "string") {
      addKeys.push(`-- skipped ${fk}`);
      continue;
    }
    addKeys.push(
      `ALTER TABLE ${qualified(fk.child, dialect)} ADD CONSTRAINT ${q(fkName(fk.child, fk.childFields))} ` +
        `FOREIGN KEY (${fk.childFields.map(q).join(", ")}) REFERENCES ${qualified(fk.parent, dialect)} (${fk.parentFields.map(q).join(", ")});`,
    );
  }
  section(addKeys);

  // 7. Enum types nothing uses any more (PostgreSQL), last, after the columns that used them.
  if (kind === "postgresql") {
    section(
      [...beforeEnums.values()]
        .filter((entry) => !afterEnums.has(entry.id))
        .map((entry) => `DROP TYPE IF EXISTS ${q(entry.name)};`),
    );
  }

  if (out.length === 0) return "";
  const header = `-- ${kind === "mysql" ? "MySQL" : "PostgreSQL"} migration — generated by CodeFlow from two DBML schemas`;
  return [header, "", ...out].join("\n").trimEnd() + "\n";
}
