import {
  Activity,
  AlarmClock,
  Archive,
  ArrowDownUp,
  ArrowRight,
  Bell,
  Blocks,
  Bot,
  Box,
  Boxes,
  Braces,
  Cable,
  Calendar,
  CircleDashed,
  CirclePlay,
  ClipboardList,
  CloudUpload,
  CodeXml,
  Container,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileArchive,
  FileBraces,
  FileCode,
  FileSpreadsheet,
  FileText,
  Folder,
  FolderGit2,
  FolderOpen,
  Funnel,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitCompare,
  GitFork,
  GitPullRequest,
  Globe,
  HardDrive,
  Hourglass,
  Key,
  KeyRound,
  Keyboard,
  Layers,
  Link,
  ListChecks,
  Mail,
  Merge,
  MessageSquareText,
  Monitor,
  MousePointerClick,
  Network,
  NotebookPen,
  OctagonX,
  Pencil,
  Play,
  Plug,
  Radio,
  RadioTower,
  RectangleEllipsis,
  Regex,
  Repeat,
  Route,
  Rss,
  Scissors,
  Server,
  ShieldCheck,
  Shuffle,
  Sigma,
  Smartphone,
  Split,
  SquareFunction,
  SquareTerminal,
  Terminal,
  Trash2,
  TriangleAlert,
  UserCheck,
  Variable,
  Webhook,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { FlowFamily } from "../tauri/flowsCommands";

/**
 * The glyph for each `icon` name the node catalogue uses (`src-tauri/src/flows/catalog.rs`).
 *
 * Named imports rather than lucide's dynamic icon, so the bundle carries the eighty glyphs it draws
 * and not the four thousand it could. A name missing here falls back to `Box` rather than to
 * nothing: a node with the wrong picture is still a node you can see and delete.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  archive: Archive,
  "arrow-down-up": ArrowDownUp,
  "arrow-right": ArrowRight,
  bell: Bell,
  blocks: Blocks,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  cable: Cable,
  calendar: Calendar,
  "circle-dashed": CircleDashed,
  "circle-play": CirclePlay,
  "clipboard-list": ClipboardList,
  "cloud-upload": CloudUpload,
  "code-xml": CodeXml,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "file-archive": FileArchive,
  "file-braces": FileBraces,
  "file-code": FileCode,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "folder-open": FolderOpen,
  funnel: Funnel,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-compare": GitCompare,
  "git-fork": GitFork,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "hard-drive": HardDrive,
  hourglass: Hourglass,
  key: Key,
  "key-round": KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  link: Link,
  "list-checks": ListChecks,
  mail: Mail,
  merge: Merge,
  "message-square-text": MessageSquareText,
  monitor: Monitor,
  "mouse-pointer-click": MousePointerClick,
  network: Network,
  "notebook-pen": NotebookPen,
  "octagon-x": OctagonX,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  radio: Radio,
  "radio-tower": RadioTower,
  "rectangle-ellipsis": RectangleEllipsis,
  regex: Regex,
  repeat: Repeat,
  route: Route,
  rss: Rss,
  scissors: Scissors,
  server: Server,
  "shield-check": ShieldCheck,
  shuffle: Shuffle,
  sigma: Sigma,
  smartphone: Smartphone,
  split: Split,
  "square-function": SquareFunction,
  "square-terminal": SquareTerminal,
  terminal: Terminal,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "user-check": UserCheck,
  variable: Variable,
  webhook: Webhook,
  zap: Zap,
};

export function nodeIcon(name: string): LucideIcon {
  return ICONS[name] ?? Box;
}

/** The palette section's own glyph. */
export const FAMILY_ICON: Record<FlowFamily, LucideIcon> = {
  trigger: Zap,
  ai: Bot,
  code: SquareTerminal,
  net: Globe,
  data: Database,
  logic: Split,
  transform: Shuffle,
  files: FolderGit2,
  app: Layers,
};

/** The palette order of the nine sections — the catalogue's own order. */
export const FAMILIES: FlowFamily[] = ["trigger", "ai", "code", "net", "data", "logic", "transform", "files", "app"];

/** The hue each family's tiles wear, as a CSS colour. Light and dark values live in `index.css`. */
export const familyColor = (family: FlowFamily) => `var(--cf-flow-${family})`;
