import {
  Activity,
  AlarmClock,
  AppWindow,
  AppWindowMac,
  Archive,
  ArrowDownUp,
  ArrowRight,
  AudioLines,
  BadgeCheck,
  Bell,
  Binary,
  Blocks,
  BookMarked,
  BookOpenText,
  Bot,
  BotMessageSquare,
  Box,
  Boxes,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  Cable,
  Calendar,
  CalendarClock,
  CalendarDays,
  CircleCheckBig,
  CircleDashed,
  CirclePlay,
  ClipboardCopy,
  ClipboardList,
  ClipboardPenLine,
  Cloud,
  CloudUpload,
  CodeXml,
  Columns3,
  Command,
  Container,
  Copy,
  Cpu,
  Database,
  DatabaseZap,
  Dices,
  Diff,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileArchive,
  FileBraces,
  FileCode,
  FileJson,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileType,
  Film,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderSync,
  Funnel,
  Gauge,
  Gavel,
  GitBranch,
  GitCommitHorizontal,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  Globe,
  HardDrive,
  Hash,
  Hourglass,
  Image,
  ImagePlus,
  Inbox,
  Key,
  Keyboard,
  KeyRound,
  Layers,
  LayoutGrid,
  Library,
  Link,
  Link2,
  ListChecks,
  ListEnd,
  ListStart,
  Mail,
  Mails,
  Menu,
  Merge,
  MessageCircle,
  MessageSquareCode,
  MessageSquareReply,
  MessageSquareText,
  MessagesSquare,
  Monitor,
  MonitorCog,
  MousePointerClick,
  Network,
  Newspaper,
  NotebookPen,
  OctagonX,
  Package,
  Pencil,
  Play,
  Plug,
  Power,
  Radar,
  Radio,
  RadioReceiver,
  RadioTower,
  RectangleEllipsis,
  Regex,
  Repeat,
  Reply,
  Rocket,
  Route,
  Rss,
  ScanEye,
  ScanSearch,
  ScanText,
  Scissors,
  ScrollText,
  Search,
  Send,
  Server,
  Sheet,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShipWheel,
  Shuffle,
  Sigma,
  Smartphone,
  Sparkles,
  Split,
  SquareFunction,
  SquareTerminal,
  Table,
  Table2,
  Tag,
  Tags,
  Terminal,
  Timer,
  Trash2,
  TriangleAlert,
  UserCheck,
  Variable,
  Volume2,
  Wand,
  WandSparkles,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { FlowFamily } from "../tauri/flowsCommands";

/**
 * The glyph for each `icon` name the node catalogue uses (`src-tauri/src/flows/catalog.rs`).
 *
 * Named imports rather than lucide's dynamic icon, so the bundle carries the hundred and sixty glyphs it draws
 * and not the four thousand it could. A name missing here falls back to `Box` rather than to
 * nothing: a node with the wrong picture is still a node you can see and delete.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  "app-window": AppWindow,
  "app-window-mac": AppWindowMac,
  archive: Archive,
  "arrow-down-up": ArrowDownUp,
  "arrow-right": ArrowRight,
  "audio-lines": AudioLines,
  "badge-check": BadgeCheck,
  bell: Bell,
  binary: Binary,
  blocks: Blocks,
  "book-marked": BookMarked,
  "book-open-text": BookOpenText,
  bot: Bot,
  "bot-message-square": BotMessageSquare,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  "brain-circuit": BrainCircuit,
  "briefcase-business": BriefcaseBusiness,
  cable: Cable,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "circle-check-big": CircleCheckBig,
  "circle-dashed": CircleDashed,
  "circle-play": CirclePlay,
  "clipboard-copy": ClipboardCopy,
  "clipboard-list": ClipboardList,
  "clipboard-pen-line": ClipboardPenLine,
  cloud: Cloud,
  "cloud-upload": CloudUpload,
  "code-xml": CodeXml,
  "columns-3": Columns3,
  command: Command,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "database-zap": DatabaseZap,
  dices: Dices,
  diff: Diff,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "file-archive": FileArchive,
  "file-braces": FileBraces,
  "file-code": FileCode,
  "file-json": FileJson,
  "file-pen": FilePen,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "file-type": FileType,
  film: Film,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "folder-open": FolderOpen,
  "folder-sync": FolderSync,
  funnel: Funnel,
  gauge: Gauge,
  gavel: Gavel,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-compare": GitCompare,
  "git-compare-arrows": GitCompareArrows,
  "git-fork": GitFork,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-pull-request-arrow": GitPullRequestArrow,
  globe: Globe,
  "hard-drive": HardDrive,
  hash: Hash,
  hourglass: Hourglass,
  image: Image,
  "image-plus": ImagePlus,
  inbox: Inbox,
  key: Key,
  "key-round": KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  "layout-grid": LayoutGrid,
  library: Library,
  link: Link,
  "link-2": Link2,
  "list-checks": ListChecks,
  "list-end": ListEnd,
  "list-start": ListStart,
  mail: Mail,
  mails: Mails,
  menu: Menu,
  merge: Merge,
  "message-circle": MessageCircle,
  "message-square-code": MessageSquareCode,
  "message-square-reply": MessageSquareReply,
  "message-square-text": MessageSquareText,
  "messages-square": MessagesSquare,
  monitor: Monitor,
  "monitor-cog": MonitorCog,
  "mouse-pointer-click": MousePointerClick,
  network: Network,
  newspaper: Newspaper,
  "notebook-pen": NotebookPen,
  "octagon-x": OctagonX,
  package: Package,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  power: Power,
  radar: Radar,
  radio: Radio,
  "radio-receiver": RadioReceiver,
  "radio-tower": RadioTower,
  "rectangle-ellipsis": RectangleEllipsis,
  regex: Regex,
  repeat: Repeat,
  reply: Reply,
  rocket: Rocket,
  route: Route,
  rss: Rss,
  "scan-eye": ScanEye,
  "scan-search": ScanSearch,
  "scan-text": ScanText,
  scissors: Scissors,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  sheet: Sheet,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-half": ShieldHalf,
  "ship-wheel": ShipWheel,
  shuffle: Shuffle,
  sigma: Sigma,
  smartphone: Smartphone,
  sparkles: Sparkles,
  split: Split,
  "square-function": SquareFunction,
  "square-terminal": SquareTerminal,
  table: Table,
  "table-2": Table2,
  tag: Tag,
  tags: Tags,
  terminal: Terminal,
  timer: Timer,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "user-check": UserCheck,
  variable: Variable,
  "volume-2": Volume2,
  wand: Wand,
  "wand-sparkles": WandSparkles,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

export function nodeIcon(name: string): LucideIcon {
  return ICONS[name] ?? Box;
}

/** The palette section's own glyph. */
export const FAMILY_ICON: Record<FlowFamily, LucideIcon> = {
  trigger: Zap,
  ai: Bot,
  code: SquareTerminal,
  git: GitBranch,
  net: Globe,
  messaging: Mail,
  apps: LayoutGrid,
  data: Database,
  files: Folder,
  logic: Split,
  transform: Shuffle,
  app: Layers,
};

/**
 * The palette order of the twelve sections. A node's section is its descriptor's `family`, never
 * its id's prefix — `files.git` is shown under Git, `net.email` under Messaging (see `Family` in
 * `catalog.rs`).
 */
export const FAMILIES: FlowFamily[] = ["trigger", "ai", "code", "git", "net", "messaging", "apps", "data", "files", "logic", "transform", "app"];

/** The hue each family's tiles wear, as a CSS colour. Light and dark values live in `index.css`. */
export const familyColor = (family: FlowFamily) => `var(--cf-flow-${family})`;
