//! The Grok Build CLI engine (`grok`), headless only.
//!
//! Verified against **grok 0.2.117** on macOS — every flag and every shape below was read off the
//! real binary, not from documentation:
//!
//!   - `grok -p "<prompt>"` runs one turn non-interactively and exits. `--single` is its long form.
//!     The app never starts the TUI; `-p` / `--prompt-file` is the only way in.
//!   - `--output-format json` prints a single JSON object on stdout. That is what this engine asks
//!     for, because it answers three questions the plain text form cannot:
//!       * `text` — the reply.
//!       * `sessionId` — the conversation, **generated by the CLI when we don't name one**, which
//!         is what lets chat resume the right conversation rather than "the last one" (see below).
//!       * `modelUsage` — keyed by the model ids actually used, so a turn can record what answered
//!         it instead of echoing back whatever was configured.
//!   - `--prompt-file <path>` takes the whole prompt from a file. This is the flag the sibling
//!     engines wish they had: no argv length limit to dance around, and — unlike `gemini.rs`'s
//!     temp-file workaround — the file is the *prompt*, not a file the agent has to be granted
//!     permission to open. Used above [`INLINE_LIMIT`]; below it the prompt rides on `-p`. The file
//!     is private and deleted when the run ends (see `crate::ai_prompt_files`).
//!   - `--resume <id>` resumes by id, and `--output-format json` echoes the same id back.
//!     Confirmed end to end: a first turn told it a word, a second turn resumed that id and
//!     recalled it. So this engine gets **real per-conversation sessions** — no `--continue`
//!     sentinel like `gemini.rs`, and no chance of two chats on one project crossing.
//!   - `--always-approve` auto-approves tool execution, which is what
//!     [`AiInvocation::auto_approve_edits`] means here. Runs are headless, so an interactive
//!     permission prompt could never be answered anyway.
//!   - `grok models` lists what the account can reach — but as prose, not one id per line, which is
//!     why this engine overrides [`AiEngine::parse_models`]. See [`parse_model_list`].
//!
//! **Not used, deliberately:** `--no-auto-update` appears in third-party write-ups of this CLI but
//! not in `grok --help` on 0.2.117. Passing a flag this binary may not know, to save a background
//! version check, is a bad trade — a hard startup failure in exchange for milliseconds.
//!
//! **`--tools` is used, and it is what makes a read-only run read-only.** Re-verified against
//! **grok 1.0.4** (`grok --help`, and the headless-mode page it ships in
//! `~/.grok/docs/user-guide/14-headless-mode.md`): `--tools <TOOLS>` is a comma-separated
//! allow-list of built-in tool **ids** — `read_file`, `grep`, `list_dir`, `web_search`,
//! `web_fetch`, `search_replace`, `run_terminal_cmd`, `todo_write`, `task` — and "only the listed
//! tools will be available". Named with those ids, never with Claude's (`Read`, `Grep`), which it
//! would not recognise. The docs add one gap: "MCP meta-tools remain available unless denied", so a
//! read-only run also passes `--deny MCPTool` — a permission rule ("deny wins over every other
//! rule", even over always-approve), in the rule syntax the same docs define, whose worst case if a
//! future build stopped recognising it is a warning rather than a failed run.
//!
//! **`--sandbox read-only` is kernel-enforced and deliberately not used.** A session's sandbox is
//! saved with it and a *different* profile on `--resume` is refused with an error, so a
//! conversation started read-only could never write again after the user switched file generation
//! on — and one started without it would fail to resume. The tool allow-list carries the guarantee
//! without that trap.

use tokio::process::Command;

use crate::ai::{quota_signal, refusal_reply, AiEngine, AiInvocation, AiRun, AiUsage, QUOTA_MARKER};

const DEFAULT_BINARY: &str = "grok";

/// Let grok pick its own model for commit messages. Which ids an account can reach depends on the
/// plan — this one exposes only `grok-4.5` — so naming one here would break for anybody whose
/// subscription exposes a different set.
const COMMIT_MESSAGE_MODEL: &str = "";

/// Above this many chars the prompt goes to a temp file and rides on `--prompt-file` instead of
/// `-p`. A PR-review diff alone can reach 120k, well past the ~32k Windows command-line limit.
const INLINE_LIMIT: usize = 12_000;

pub struct GrokEngine;

impl AiEngine for GrokEngine {
    /// Grok reads project skills from both `.agents/skills` and `.claude/skills` (its guide's skills
    /// page, and `grok inspect` in a folder holding each). Pointed at the Claude one so a repository,
    /// which the app syncs there, needs no second copy — and so no skill is listed to it twice.
    fn native_skills_dir(&self) -> Option<&'static str> {
        Some(".claude/skills")
    }

    fn id(&self) -> &'static str {
        "grok"
    }

    fn label(&self) -> &'static str {
        "Grok"
    }

    fn default_binary(&self) -> &'static str {
        DEFAULT_BINARY
    }

    fn commit_message_model(&self) -> &'static str {
        COMMIT_MESSAGE_MODEL
    }

    fn fix_tools(&self) -> Vec<String> {
        // Write access comes from `--always-approve`, not from naming tools — see the module docs.
        Vec::new()
    }

    fn build_command(&self, binary: &str, inv: &AiInvocation) -> Command {
        let mut cmd = crate::proc::command(binary);

        // System instructions → the ask → the data payload, as one brief. Grok has
        // `--system-prompt-override`, but that *replaces* the agent's own system prompt rather than
        // adding to it, which would strip the instructions that make its tools work.
        let mut brief = String::new();
        if let Some(sp) = inv.system_prompt {
            if !sp.trim().is_empty() {
                brief.push_str(sp);
                brief.push_str("\n\n");
            }
        }
        brief.push_str(inv.prompt);
        if !inv.stdin_content.trim().is_empty() {
            brief.push_str("\n\n----- INPUT -----\n\n");
            brief.push_str(inv.stdin_content);
        }

        match write_brief_file_if_unsafe_inline(inv, &brief) {
            Some(file) => {
                cmd.arg("--prompt-file").arg(file);
            }
            None => {
                cmd.arg("-p").arg(&brief);
            }
        }

        cmd.arg("--output-format").arg("json");

        if !inv.model.trim().is_empty() {
            cmd.arg("--model").arg(inv.model);
        }
        if inv.auto_approve_edits && !inv.read_only {
            cmd.arg("--always-approve");
        }
        // The allow-list. `--tools` is comma-separated and, per grok's own docs, leaves only the
        // listed tools available — so naming a read-only set here is what actually takes
        // `search_replace` and `run_terminal_cmd` away from a conversation that was promised it
        // could not write. A read-only run always gets this engine's own set, whatever the caller
        // passed, plus the one rule the allow-list does not cover: MCP tools. See the module docs.
        if inv.read_only {
            cmd.arg("--tools").arg(self.read_only_tools().join(","));
            cmd.arg("--deny").arg("MCPTool");
        } else if !inv.allowed_tools.is_empty() {
            cmd.arg("--tools").arg(inv.allowed_tools.join(","));
        }
        // The final answer must satisfy this schema (grok 1.0.4's `--json-schema`, which implies the
        // `json` output already chosen above). A flow node checks the answer itself either way.
        if let Some(schema) = inv.json_schema {
            cmd.arg("--json-schema").arg(schema);
        }
        // Resume by id. Not `--session-id`: that names a **new** conversation and errors if the id
        // already exists, so using it to resume would fail on the second turn of every chat.
        if let Some(session) = inv.resume_session_id {
            if !session.trim().is_empty() {
                cmd.arg("--resume").arg(session);
            }
        }
        if let Some(dir) = inv.cwd {
            cmd.current_dir(dir);
        }
        cmd
    }

    /// grok's own tool ids, from the table in its shipped headless-mode docs (re-checked on 1.0.4):
    /// the file reader is `read_file` and the directory lister `list_dir`, so Claude's vocabulary
    /// would be silently rejected here. `glob`, which this list used to carry, is not in that table
    /// — the docs' own read-only example is `read_file,grep,list_dir` — so it is left out rather
    /// than trusted to be ignored.
    ///
    /// That this engine can be limited at all was a late discovery. `--tools` and
    /// `--disallowed-tools` have been there the whole time, and both this module and
    /// `commands::chat_cmd` used to state that Claude Code was the only engine with an allow-list.
    /// It was not, and a read-only conversation on grok was running with the full agent profile —
    /// its file editor and its shell included — on the strength of a comment nobody had re-checked.
    fn read_only_tools(&self) -> Vec<String> {
        ["read_file", "grep", "list_dir", "web_search", "web_fetch"]
            .iter()
            .map(|s| s.to_string())
            .collect()
    }

    /// The allow-list is enforced by the CLI — tools outside it are not available to the model at
    /// all — and MCP calls are denied by rule. See the module docs.
    fn enforces_read_only(&self) -> bool {
        true
    }

    /// `--output-format json` prints one object when the turn is over and nothing before it, so
    /// silence is how a working grok looks. See [`AiEngine::quiet_while_working`].
    fn quiet_while_working(&self) -> bool {
        true
    }

    /// A failed turn that got as far as printing its object still carries `usage`.
    fn reported_usage(&self, stdout: &str, _stderr: &str) -> Option<AiUsage> {
        let reply = serde_json::from_str::<GrokReply>(stdout.trim()).ok()?;
        reply.usage.as_ref().map(|u| usage_of(u, reply.total_cost_usd))
    }

    /// `grok --reasoning-effort <EFFORT>` (aliased `--effort`). The CLI's help does not enumerate
    /// the accepted values, so the neutral level is passed through unchanged and `max` is sent as
    /// `high` — the highest level every reasoning vocabulary in circulation agrees on. If a future
    /// build documents its own top step, this is the one line that changes.
    fn effort_args(&self, effort: &str) -> Vec<String> {
        let level = if effort == crate::ai::effort::MAX { "high" } else { effort };
        vec!["--reasoning-effort".into(), level.into()]
    }

    fn interpret(&self, success: bool, status_label: &str, stdout: &str, stderr: &str) -> Result<AiRun, String> {
        interpret_output(success, status_label, stdout, stderr)
    }

    fn list_models_args(&self) -> Option<Vec<String>> {
        Some(vec!["models".to_string()])
    }

    fn parse_models(&self, stdout: &str) -> Vec<String> {
        parse_model_list(stdout)
    }
}

/// Returns `Some(path)` when `content` is unsafe or too big to pass inline and was written to a
/// temp file; `None` when it fits on the command line as-is. A failed write also returns `None`,
/// degrading to an inline attempt rather than failing the call outright.
///
/// Two reasons content can't ride on `-p`, not just one: past [`INLINE_LIMIT`] it risks the
/// ~32k Windows command-line ceiling (a review diff alone can reach 120k) — but a *short* brief
/// with an embedded newline (any system prompt, or `stdin_content` folded in below it) is just as
/// unsafe if this binary is ever resolved through an npm `.cmd` shim on Windows, which routes
/// through `cmd.exe` and rejects multi-line arguments outright (see `claude.rs`, which hit exactly
/// this). Routing those through `--prompt-file` too costs one private file write and closes the
/// gap regardless of which case applies to a given install. The file goes when the run ends.
fn write_brief_file_if_unsafe_inline(inv: &AiInvocation, content: &str) -> Option<std::path::PathBuf> {
    if content.len() <= INLINE_LIMIT && !content.contains('\n') {
        return None;
    }
    inv.prompt_files.write("grok", "txt", content)
}

/// One reply's usage, in this app's terms.
fn usage_of(u: &GrokUsage, cost_usd: Option<f64>) -> AiUsage {
    AiUsage {
        input_tokens: u.input_tokens,
        output_tokens: u.output_tokens,
        cache_read_tokens: u.cache_read_input_tokens,
        cache_write_tokens: 0,
        cost_usd,
    }
}

/// Pulls the model ids out of `grok models`, which reports for humans rather than for scripts:
///
/// ```text
/// You are logged in with grok.com.
///
/// Default model: grok-4.5
///
/// Available models:
///   * grok-4.5 (default)
/// ```
///
/// Only the bulleted lines are ids — anchoring on the bullet rather than on the "Available models:"
/// heading keeps this working if the surrounding prose is reworded or translated, and it is what
/// excludes the `Default model:` line, which names a real id but is not an entry in the list.
fn parse_model_list(stdout: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for line in stdout.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("* ").or_else(|| line.strip_prefix("- ")) else {
            continue;
        };
        // `grok-4.5 (default)` → `grok-4.5`. An id never contains a space, so the first one ends it.
        let id = rest.split_whitespace().next().unwrap_or_default();
        if !id.is_empty() && !ids.iter().any(|seen| seen == id) {
            ids.push(id.to_string());
        }
    }
    ids
}

/// The shape of `--output-format json`. Only the fields this app acts on are named; the rest
/// (`usage`, `total_cost_usd`, `requestId`, `thought`, …) are ignored rather than modelled, so a
/// new field upstream can't fail the parse.
#[derive(serde::Deserialize)]
struct GrokReply {
    #[serde(default)]
    text: String,
    #[serde(default, rename = "sessionId")]
    session_id: Option<String>,
    #[serde(default, rename = "modelUsage")]
    model_usage: std::collections::BTreeMap<String, serde_json::Value>,
    /// The turn's own token counts. Defaulted field by field for the same reason Claude's are: a
    /// CLI that adds one to this object must not take the whole reply down with it.
    #[serde(default)]
    usage: Option<GrokUsage>,
    #[serde(default)]
    total_cost_usd: Option<f64>,
}

#[derive(Default, serde::Deserialize)]
struct GrokUsage {
    #[serde(default)]
    input_tokens: i64,
    #[serde(default)]
    output_tokens: i64,
    #[serde(default)]
    cache_read_input_tokens: i64,
}

/// Grok prints one JSON object on stdout in headless mode; banners and errors go to stderr.
fn interpret_output(
    success: bool,
    status_label: &str,
    stdout: &str,
    stderr: &str,
) -> Result<AiRun, String> {
    if !success {
        if quota_signal(stderr) {
            return Err(format!("{QUOTA_MARKER}{}", stderr.trim()));
        }
        if quota_signal(stdout) {
            return Err(format!("{QUOTA_MARKER}{}", stdout.trim()));
        }
        let detail = [stderr.trim(), stdout.trim()]
            .into_iter()
            .find(|s| !s.is_empty())
            .unwrap_or("no output on stdout or stderr");
        return Err(format!("grok exited with an error ({status_label}): {detail}"));
    }

    let raw = stdout.trim();
    if raw.is_empty() {
        let err = stderr.trim();
        return Err(if err.is_empty() {
            "grok produced no output".to_string()
        } else {
            err.to_string()
        });
    }

    // A clean exit whose stdout isn't the JSON we asked for means something printed over it. Fall
    // back to treating stdout as the reply rather than failing: a usable answer in the wrong shape
    // still beats an error, and this is also what a future `--output-format` change would look like.
    let Ok(reply) = serde_json::from_str::<GrokReply>(raw) else {
        if refusal_reply(raw, None) {
            return Err(format!("{QUOTA_MARKER}{raw}"));
        }
        return Ok(AiRun { text: raw.to_string(), session_id: None, model: None, usage: None, context_tokens: None });
    };

    let text = reply.text.trim();
    if text.is_empty() {
        return Err("grok produced no output".to_string());
    }
    if refusal_reply(text, reply.usage.as_ref().map(|u| u.output_tokens)) {
        return Err(format!("{QUOTA_MARKER}{text}"));
    }

    // Only when exactly one model answered. A turn that fanned out across several has no single
    // honest answer to "what ran this", and the caller's fallback (the configured id) is better
    // than naming whichever happened to sort first.
    let model = match reply.model_usage.len() {
        1 => reply.model_usage.keys().next().cloned(),
        _ => None,
    };

    let usage = reply.usage.as_ref().map(|u| usage_of(u, reply.total_cost_usd));

    Ok(AiRun {
        text: text.to_string(),
        session_id: reply.session_id.filter(|s| !s.trim().is_empty()),
        model,
        usage: usage.filter(|u| !u.is_empty()),
        // `None`: this app does not read this CLI's output step by step, so it has no
        // figure for the *final* prompt — only a cumulative total, which is a bill and not a
        // gauge. The chat's context meter estimates instead, and says so.
        context_tokens: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Captured verbatim from `grok -p … --output-format json` on 0.2.117, trimmed to the fields
    /// this engine reads.
    const SAMPLE: &str = r#"{
      "text": "OK",
      "stopReason": "end_turn",
      "sessionId": "019fb616-cde1-7a51-9aec-aa06273c4552",
      "requestId": "aee555aa-043a-4f56-b7d2-b68ca5de469e",
      "usage": { "input_tokens": 13820, "output_tokens": 22 },
      "num_turns": 1,
      "total_cost_usd": 0.0280792,
      "modelUsage": { "grok-4.5": { "inputTokens": 13820, "outputTokens": 22 } }
    }"#;

    #[test]
    fn reads_reply_session_and_model_from_the_json() {
        let run = interpret_output(true, "exit status: 0", SAMPLE, "").unwrap();
        assert_eq!(run.text, "OK");
        assert_eq!(run.session_id.as_deref(), Some("019fb616-cde1-7a51-9aec-aa06273c4552"));
        assert_eq!(run.model.as_deref(), Some("grok-4.5"));
    }

    #[test]
    fn a_fan_out_across_models_reports_none_rather_than_guessing() {
        let json = r#"{"text":"hi","modelUsage":{"grok-4.5":{},"grok-4.5-fast":{}}}"#;
        assert!(interpret_output(true, "exit status: 0", json, "").unwrap().model.is_none());
    }

    #[test]
    fn non_json_stdout_on_a_clean_exit_is_still_treated_as_the_reply() {
        let run = interpret_output(true, "exit status: 0", "plain words", "").unwrap();
        assert_eq!(run.text, "plain words");
        assert!(run.session_id.is_none());
    }

    #[test]
    fn surfaces_the_failure_detail() {
        let err = interpret_output(false, "exit status: 1", "", "not signed in — run `grok login`").unwrap_err();
        assert_eq!(err, "grok exited with an error (exit status: 1): not signed in — run `grok login`");
    }

    #[test]
    fn a_quota_message_gets_the_marker() {
        let err = interpret_output(false, "exit status: 1", "", "rate limit exceeded, try again later").unwrap_err();
        assert!(err.starts_with(QUOTA_MARKER), "got {err}");
    }

    #[test]
    fn empty_output_on_a_clean_exit_is_an_error_not_a_blank_reply() {
        let err = interpret_output(true, "exit status: 0", "   ", "").unwrap_err();
        assert_eq!(err, "grok produced no output");
    }

    /// The real output of `grok models` on 0.2.117, verbatim.
    #[test]
    fn parses_the_prose_model_listing() {
        let out = "You are logged in with grok.com.\n\nDefault model: grok-4.5\n\nAvailable models:\n  * grok-4.5 (default)\n";
        assert_eq!(parse_model_list(out), vec!["grok-4.5"]);
    }

    #[test]
    fn takes_every_bullet_and_ignores_the_prose_around_them() {
        let out = "Available models:\n  * grok-4.5 (default)\n  * grok-4.5-fast\n  - grok-code\n";
        assert_eq!(parse_model_list(out), vec!["grok-4.5", "grok-4.5-fast", "grok-code"]);
    }

    #[test]
    fn a_listing_with_no_bullets_yields_nothing_rather_than_prose() {
        assert!(parse_model_list("You are not logged in. Run `grok login`.").is_empty());
    }

    #[test]
    fn small_single_line_prompts_stay_inline() {
        assert!(write_brief_file_if_unsafe_inline(&AiInvocation::new("", ""), "hola").is_none());
    }

    /// A brief under `INLINE_LIMIT` still has to move to a file once it has a newline — a system
    /// prompt or folded-in `stdin_content` makes this the common case, not an edge case. And the
    /// file goes with the run that needed it.
    #[test]
    fn a_short_multiline_brief_still_moves_to_a_file() {
        let inv = AiInvocation::new("", "");
        let path = write_brief_file_if_unsafe_inline(&inv, "system prompt\n\nthe ask").expect("a file");
        assert!(path.exists());
        drop(inv);
        assert!(!path.exists(), "deleted with the invocation");
    }

    fn args_of(inv: &AiInvocation) -> Vec<String> {
        GrokEngine
            .build_command("grok", inv)
            .as_std()
            .get_args()
            .map(|a| a.to_string_lossy().into_owned())
            .collect()
    }

    /// Read-only is the allow-list of grok's own read ids plus the MCP deny, and never the
    /// always-approve — whatever list or approval the caller also passed.
    #[test]
    fn a_read_only_run_gets_the_allow_list_and_no_mcp() {
        let broad = vec!["read_file".to_string(), "search_replace".to_string()];
        let mut inv = AiInvocation::new("¿qué hace esto?", "");
        inv.allowed_tools = &broad;
        inv.auto_approve_edits = true;
        inv.read_only = true;
        let args = args_of(&inv);
        assert!(args.windows(2).any(|pair| pair == ["--tools", "read_file,grep,list_dir,web_search,web_fetch"]), "{args:?}");
        assert!(args.windows(2).any(|pair| pair == ["--deny", "MCPTool"]), "{args:?}");
        assert!(!args.iter().any(|a| a == "--always-approve"), "{args:?}");
        assert!(!args.iter().any(|a| a.contains("search_replace")), "{args:?}");
    }

    /// Every id in the read-only set is one grok's docs list as a read tool — none of them writes.
    #[test]
    fn the_read_only_set_names_only_documented_read_tools() {
        for tool in GrokEngine.read_only_tools() {
            assert!(
                ["read_file", "grep", "list_dir", "web_search", "web_fetch"].contains(&tool.as_str()),
                "{tool} is not a documented read-only tool id"
            );
        }
    }

    #[test]
    fn a_failed_turn_that_printed_its_object_reports_what_it_spent() {
        let usage = GrokEngine.reported_usage(SAMPLE, "").expect("usage");
        assert_eq!((usage.input_tokens, usage.output_tokens), (13820, 22));
        assert!(GrokEngine.reported_usage("", "not signed in").is_none());
    }
}
