//! The Grok Build CLI engine (`grok`), headless only.
//!
//! Verified against **grok 0.2.117** on macOS — every flag and every shape below was read off the
//! real binary, not from documentation:
//!
//!   - `grok -p "<prompt>"` runs one turn non-interactively and exits. `--single` is its long form.
//!     The app never starts the TUI; `-p` / `--prompt-file` is the only way in.
//!   - `--output-format json` prints a single JSON object on stdout. That is what this engine asks
//!     for, because it answers three questions the plain text form cannot:
//!       * `text` — the reply.
//!       * `sessionId` — the conversation, **generated by the CLI when we don't name one**, which
//!         is what lets chat resume the right conversation rather than "the last one" (see below).
//!       * `modelUsage` — keyed by the model ids actually used, so a turn can record what answered
//!         it instead of echoing back whatever was configured.
//!   - `--prompt-file <path>` takes the whole prompt from a file. This is the flag the sibling
//!     engines wish they had: no argv length limit to dance around, and — unlike `gemini.rs`'s
//!     temp-file workaround — the file is the *prompt*, not a file the agent has to be granted
//!     permission to open. Used above [`INLINE_LIMIT`]; below it the prompt rides on `-p`.
//!   - `--resume <id>` resumes by id, and `--output-format json` echoes the same id back.
//!     Confirmed end to end: a first turn told it a word, a second turn resumed that id and
//!     recalled it. So this engine gets **real per-conversation sessions** — no `--continue`
//!     sentinel like `gemini.rs`, and no chance of two chats on one project crossing.
//!   - `--always-approve` auto-approves tool execution, which is what
//!     [`AiInvocation::auto_approve_edits`] means here. Runs are headless, so an interactive
//!     permission prompt could never be answered anyway.
//!   - `grok models` lists what the account can reach — but as prose, not one id per line, which is
//!     why this engine overrides [`AiEngine::parse_models`]. See [`parse_model_list`].
//!
//! **Not used, deliberately:** `--no-auto-update` appears in third-party write-ups of this CLI but
//! not in `grok --help` on 0.2.117. Passing a flag this binary may not know, to save a background
//! version check, is a bad trade — a hard startup failure in exchange for milliseconds.
//!
//! `--tools` / `--allow` do exist, so a tool allow-list is technically reachable. It stays unused
//! until the rule syntax is verified the way everything above was: an allow-list that silently
//! doesn't match is worse than none, because it reads as a restriction that is in force.

use tokio::process::Command;

use crate::ai::{quota_signal, AiEngine, AiInvocation, AiRun, QUOTA_MARKER};

const DEFAULT_BINARY: &str = "grok";

/// Let grok pick its own model for commit messages. Which ids an account can reach depends on the
/// plan — this one exposes only `grok-4.5` — so naming one here would break for anybody whose
/// subscription exposes a different set.
const COMMIT_MESSAGE_MODEL: &str = "";

/// Above this many chars the prompt goes to a temp file and rides on `--prompt-file` instead of
/// `-p`. A PR-review diff alone can reach 120k, well past the ~32k Windows command-line limit.
const INLINE_LIMIT: usize = 12_000;

pub struct GrokEngine;

impl AiEngine for GrokEngine {
    fn label(&self) -> &'static str {
        "Grok"
    }

    fn default_binary(&self) -> &'static str {
        DEFAULT_BINARY
    }

    fn commit_message_model(&self) -> &'static str {
        COMMIT_MESSAGE_MODEL
    }

    fn fix_tools(&self) -> Vec<String> {
        // Write access comes from `--always-approve`, not from naming tools — see the module docs.
        Vec::new()
    }

    fn build_command(&self, binary: &str, inv: &AiInvocation) -> Command {
        let mut cmd = crate::proc::command(binary);

        // System instructions → the ask → the data payload, as one brief. Grok has
        // `--system-prompt-override`, but that *replaces* the agent's own system prompt rather than
        // adding to it, which would strip the instructions that make its tools work.
        let mut brief = String::new();
        if let Some(sp) = inv.system_prompt {
            if !sp.trim().is_empty() {
                brief.push_str(sp);
                brief.push_str("\n\n");
            }
        }
        brief.push_str(inv.prompt);
        if !inv.stdin_content.trim().is_empty() {
            brief.push_str("\n\n----- INPUT -----\n\n");
            brief.push_str(inv.stdin_content);
        }

        match write_brief_file_if_large(&brief) {
            Some(file) => {
                cmd.arg("--prompt-file").arg(file);
            }
            None => {
                cmd.arg("-p").arg(&brief);
            }
        }

        cmd.arg("--output-format").arg("json");

        if !inv.model.trim().is_empty() {
            cmd.arg("--model").arg(inv.model);
        }
        if inv.auto_approve_edits {
            cmd.arg("--always-approve");
        }
        // Resume by id. Not `--session-id`: that names a **new** conversation and errors if the id
        // already exists, so using it to resume would fail on the second turn of every chat.
        if let Some(session) = inv.resume_session_id {
            if !session.trim().is_empty() {
                cmd.arg("--resume").arg(session);
            }
        }
        if let Some(dir) = inv.cwd {
            cmd.current_dir(dir);
        }
        cmd
    }

    fn interpret(&self, success: bool, status_label: &str, stdout: &str, stderr: &str) -> Result<AiRun, String> {
        interpret_output(success, status_label, stdout, stderr)
    }

    fn list_models_args(&self) -> Option<Vec<String>> {
        Some(vec!["models".to_string()])
    }

    fn parse_models(&self, stdout: &str) -> Vec<String> {
        parse_model_list(stdout)
    }
}

/// Returns `Some(path)` when `content` is too big to pass inline and was written to a temp file;
/// `None` when it fits on the command line. A failed write also returns `None`, degrading to an
/// inline attempt rather than failing the call outright.
fn write_brief_file_if_large(content: &str) -> Option<std::path::PathBuf> {
    if content.len() <= INLINE_LIMIT {
        return None;
    }
    let file = std::env::temp_dir().join(format!("codeflow-grok-{}.txt", uuid::Uuid::new_v4()));
    std::fs::write(&file, content).ok()?;
    Some(file)
}

/// Pulls the model ids out of `grok models`, which reports for humans rather than for scripts:
///
/// ```text
/// You are logged in with grok.com.
///
/// Default model: grok-4.5
///
/// Available models:
///   * grok-4.5 (default)
/// ```
///
/// Only the bulleted lines are ids — anchoring on the bullet rather than on the "Available models:"
/// heading keeps this working if the surrounding prose is reworded or translated, and it is what
/// excludes the `Default model:` line, which names a real id but is not an entry in the list.
fn parse_model_list(stdout: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for line in stdout.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("* ").or_else(|| line.strip_prefix("- ")) else {
            continue;
        };
        // `grok-4.5 (default)` → `grok-4.5`. An id never contains a space, so the first one ends it.
        let id = rest.split_whitespace().next().unwrap_or_default();
        if !id.is_empty() && !ids.iter().any(|seen| seen == id) {
            ids.push(id.to_string());
        }
    }
    ids
}

/// The shape of `--output-format json`. Only the fields this app acts on are named; the rest
/// (`usage`, `total_cost_usd`, `requestId`, `thought`, …) are ignored rather than modelled, so a
/// new field upstream can't fail the parse.
#[derive(serde::Deserialize)]
struct GrokReply {
    #[serde(default)]
    text: String,
    #[serde(default, rename = "sessionId")]
    session_id: Option<String>,
    #[serde(default, rename = "modelUsage")]
    model_usage: std::collections::BTreeMap<String, serde_json::Value>,
}

/// Grok prints one JSON object on stdout in headless mode; banners and errors go to stderr.
fn interpret_output(
    success: bool,
    status_label: &str,
    stdout: &str,
    stderr: &str,
) -> Result<AiRun, String> {
    if !success {
        if quota_signal(stderr) {
            return Err(format!("{QUOTA_MARKER}{}", stderr.trim()));
        }
        if quota_signal(stdout) {
            return Err(format!("{QUOTA_MARKER}{}", stdout.trim()));
        }
        let detail = [stderr.trim(), stdout.trim()]
            .into_iter()
            .find(|s| !s.is_empty())
            .unwrap_or("no output on stdout or stderr");
        return Err(format!("grok exited with an error ({status_label}): {detail}"));
    }

    let raw = stdout.trim();
    if raw.is_empty() {
        let err = stderr.trim();
        return Err(if err.is_empty() {
            "grok produced no output".to_string()
        } else {
            err.to_string()
        });
    }

    // A clean exit whose stdout isn't the JSON we asked for means something printed over it. Fall
    // back to treating stdout as the reply rather than failing: a usable answer in the wrong shape
    // still beats an error, and this is also what a future `--output-format` change would look like.
    let Ok(reply) = serde_json::from_str::<GrokReply>(raw) else {
        if quota_signal(raw) {
            return Err(format!("{QUOTA_MARKER}{raw}"));
        }
        return Ok(AiRun { text: raw.to_string(), session_id: None, model: None });
    };

    let text = reply.text.trim();
    if text.is_empty() {
        return Err("grok produced no output".to_string());
    }
    if quota_signal(text) {
        return Err(format!("{QUOTA_MARKER}{text}"));
    }

    // Only when exactly one model answered. A turn that fanned out across several has no single
    // honest answer to "what ran this", and the caller's fallback (the configured id) is better
    // than naming whichever happened to sort first.
    let model = match reply.model_usage.len() {
        1 => reply.model_usage.keys().next().cloned(),
        _ => None,
    };

    Ok(AiRun {
        text: text.to_string(),
        session_id: reply.session_id.filter(|s| !s.trim().is_empty()),
        model,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Captured verbatim from `grok -p … --output-format json` on 0.2.117, trimmed to the fields
    /// this engine reads.
    const SAMPLE: &str = r#"{
      "text": "OK",
      "stopReason": "end_turn",
      "sessionId": "019fb616-cde1-7a51-9aec-aa06273c4552",
      "requestId": "aee555aa-043a-4f56-b7d2-b68ca5de469e",
      "usage": { "input_tokens": 13820, "output_tokens": 22 },
      "num_turns": 1,
      "total_cost_usd": 0.0280792,
      "modelUsage": { "grok-4.5": { "inputTokens": 13820, "outputTokens": 22 } }
    }"#;

    #[test]
    fn reads_reply_session_and_model_from_the_json() {
        let run = interpret_output(true, "exit status: 0", SAMPLE, "").unwrap();
        assert_eq!(run.text, "OK");
        assert_eq!(run.session_id.as_deref(), Some("019fb616-cde1-7a51-9aec-aa06273c4552"));
        assert_eq!(run.model.as_deref(), Some("grok-4.5"));
    }

    #[test]
    fn a_fan_out_across_models_reports_none_rather_than_guessing() {
        let json = r#"{"text":"hi","modelUsage":{"grok-4.5":{},"grok-4.5-fast":{}}}"#;
        assert!(interpret_output(true, "exit status: 0", json, "").unwrap().model.is_none());
    }

    #[test]
    fn non_json_stdout_on_a_clean_exit_is_still_treated_as_the_reply() {
        let run = interpret_output(true, "exit status: 0", "plain words", "").unwrap();
        assert_eq!(run.text, "plain words");
        assert!(run.session_id.is_none());
    }

    #[test]
    fn surfaces_the_failure_detail() {
        let err = interpret_output(false, "exit status: 1", "", "not signed in — run `grok login`").unwrap_err();
        assert_eq!(err, "grok exited with an error (exit status: 1): not signed in — run `grok login`");
    }

    #[test]
    fn a_quota_message_gets_the_marker() {
        let err = interpret_output(false, "exit status: 1", "", "rate limit exceeded, try again later").unwrap_err();
        assert!(err.starts_with(QUOTA_MARKER), "got {err}");
    }

    #[test]
    fn empty_output_on_a_clean_exit_is_an_error_not_a_blank_reply() {
        let err = interpret_output(true, "exit status: 0", "   ", "").unwrap_err();
        assert_eq!(err, "grok produced no output");
    }

    /// The real output of `grok models` on 0.2.117, verbatim.
    #[test]
    fn parses_the_prose_model_listing() {
        let out = "You are logged in with grok.com.\n\nDefault model: grok-4.5\n\nAvailable models:\n  * grok-4.5 (default)\n";
        assert_eq!(parse_model_list(out), vec!["grok-4.5"]);
    }

    #[test]
    fn takes_every_bullet_and_ignores_the_prose_around_them() {
        let out = "Available models:\n  * grok-4.5 (default)\n  * grok-4.5-fast\n  - grok-code\n";
        assert_eq!(parse_model_list(out), vec!["grok-4.5", "grok-4.5-fast", "grok-code"]);
    }

    #[test]
    fn a_listing_with_no_bullets_yields_nothing_rather_than_prose() {
        assert!(parse_model_list("You are not logged in. Run `grok login`.").is_empty());
    }

    #[test]
    fn small_prompts_stay_inline() {
        assert!(write_brief_file_if_large("hola").is_none());
    }
}
